---
title: "Project1Initial"
author: "Isabelle Meredith"
date: "2026-02-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(naniar)
library(tidyr)
library(brms)
library(bayesplot)
```

## R Markdown


```{r}
dfHIV <- read.csv("./DataRaw/hiv_6624_final.csv") %>% 
  filter(years == 0 | years == 2)

# count subjects before dropping missing
nrow(dfHIV %>% group_by(newid) %>% summarise(n=n()))

dfHIV <- dfHIV %>% select(newid, AGG_MENT, AGG_PHYS, BMI, SMOKE, LEU3N, VLOAD, RACE, EDUCBAS, age, ADH, years, hard_drugs) 

dfHIV <- dfHIV %>% pivot_wider(names_from = years, values_from = c(AGG_MENT, AGG_PHYS, BMI, SMOKE, LEU3N, VLOAD, RACE, EDUCBAS, age, ADH, hard_drugs)) %>%
  filter(!(is.na(AGG_MENT_0) | is.na(AGG_MENT_2) | is.na(AGG_PHYS_0)| is.na(AGG_PHYS_2) | is.na(LEU3N_0) | is.na(LEU3N_2) | is.na(VLOAD_0) | is.na(VLOAD_2))) 

nrow(dfHIV %>% filter((BMI_0 > 100) | (BMI_0 < 0)))

# adherences top 2 vs bottom 2 categories
# current smopker vs not current smoker

dfHIV <- dfHIV %>%
  mutate(BMI_0 = ifelse((BMI_0 > 100) | (BMI_0 < 0), NA, BMI_0),
         logVLOAD_0 = log(VLOAD_0, base=10),
         logVLOAD_2 = log(VLOAD_2, base=10),
         MENT_DIFF = AGG_MENT_2 - AGG_MENT_0,
         PHYS_DIFF = AGG_PHYS_2 - AGG_PHYS_0,
         logVLOAD_DIFF = logVLOAD_2 - logVLOAD_0,
         LEU3N_DIFF = LEU3N_2 - LEU3N_0,
         collegeDegree = ifelse(EDUCBAS_0 <= 4, 0, 1),
         white = ifelse(RACE_0 == 1, 1, 0),
         smoker = ifelse(SMOKE_0 == 3, 1, 0),
         adherenceHigh = ifelse(ADH_2 < 3, 0, 1)) %>% 
  select(-c(BMI_2, SMOKE_2, RACE_2, EDUCBAS_2, age_2, ADH_0, hard_drugs_2)) %>%
  filter(!is.na(BMI_0))

nrow(dfHIV)
```
```{r}
plot_diagnostics_lm <- function(x, model) {
  par(mfrow=c(2,2), mar=c(4.1,4.1,3.1,2.1))
  plot(x=x, y=rstudent(model), xlab='Predictor', ylab='Jackknife Residual', 
     main='Residual Plot by X', cex=1); abline(h=0, lty=2, col='gray65')
  ## Scatterplot of residuals by predicted values
  plot(x=predict(model), y=rstudent(model), xlab=expression(hat(Y)), ylab='Jackknife Residual',
       main='Residual Plot by Y-hat', cex=1); abline(h=0, lty=2, col='gray65')
  
  ## Histogram of jackknife residuals with normal curve
  hist(rstudent(model), xlab='Jackknife Residual', 
       main='Histogram of Residuals', freq=F, breaks=seq(-10,10,0.25)); 
    curve( dnorm(x,mean=0,sd=1), lwd=2, col='blue', add=T)
  
  ## QQ-plot
  qqnorm( rstudent(model) ); qqline( rstudent(model) )
}
```

```{r}
# Comparison models with no hard drugs variable
modelMentalFrequentistComparison <- lm(MENT_DIFF ~ AGG_MENT_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelMentalFrequentistComparison)

modelPhysicalFrequentistComparison <- lm(PHYS_DIFF ~ hard_drugs_0 + AGG_PHYS_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelPhysicalFrequentistComparison)

modelTCellsFrequentistComparison <- lm(LEU3N_DIFF ~ hard_drugs_0 + LEU3N_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelTCellsFrequentistComparison)

modellogVLoadFrequentistComparison <- lm(logVLOAD_DIFF ~ hard_drugs_0 + logVLOAD_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modellogVLoadFrequentistComparison)
```

```{r}
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelMentalFrequentistComparison)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelPhysicalFrequentistComparison)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelTCellsFrequentistComparison)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modellogVLoadFrequentistComparison)
```

```{r}
# Base models with no adherence
modelMentalFrequentist <- lm(MENT_DIFF ~ hard_drugs_0 + AGG_MENT_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelMentalFrequentist)

modelPhysicalFrequentist <- lm(PHYS_DIFF ~ hard_drugs_0 + AGG_PHYS_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelPhysicalFrequentist)

modelTCellsFrequentist <- lm(LEU3N_DIFF ~ hard_drugs_0 + LEU3N_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelTCellsFrequentist)

modellogVLoadFrequentist <- lm(logVLOAD_DIFF ~ hard_drugs_0 + logVLOAD_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modellogVLoadFrequentist)
```

```{r}
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelMentalFrequentist)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelPhysicalFrequentist)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelTCellsFrequentist)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modellogVLoadFrequentist)
```



```{r}
# Models with adherence
modelMentalFrequentistADH <- lm(MENT_DIFF ~ hard_drugs_0 + adherenceHigh + AGG_MENT_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelMentalFrequentistADH)

modelPhysicalFrequentistADH <- lm(PHYS_DIFF ~ hard_drugs_0 + adherenceHigh + AGG_PHYS_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelPhysicalFrequentistADH)

modelTCellsFrequentistADH <- lm(LEU3N_DIFF ~ hard_drugs_0 + adherenceHigh + LEU3N_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modelTCellsFrequentistADH)

modellogVLoadFrequentistADH <- lm(logVLOAD_DIFF ~ hard_drugs_0 + adherenceHigh + logVLOAD_0 + age_0 + BMI_0 + white + smoker + collegeDegree, data=dfHIV)
summary(modellogVLoadFrequentistADH)
```

```{r}
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelMentalFrequentistADH)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelPhysicalFrequentistADH)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modelTCellsFrequentistADH)
plot_diagnostics_lm(dfHIV$hard_drugs_0, modellogVLoadFrequentistADH)
```

```{r}
# Comparison models with no hard drugs variable
# set priors
priors <- c(
  set_prior("normal(0, 100)", class="b"),
  set_prior("normal(0, 100)", class="Intercept"),
  set_prior("normal(0, 100)", class="sigma", lb=0))
modelMentalBayesianComparison <- brm(MENT_DIFF ~ AGG_MENT_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelMentalBayesianComparison)

modelPhysicalBayesianComparison <- brm(PHYS_DIFF ~ AGG_PHYS_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelPhysicalBayesianComparison)

modelTCellsBayesianComparison <- brm(LEU3N_DIFF ~ LEU3N_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelTCellsBayesianComparison)

modellogVLoadBayesianComparison <- brm(logVLOAD_DIFF ~ logVLOAD_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modellogVLoadBayesianComparison)
```

```{r}
plot(modelMentalBayesianComparison)
plot(modelPhysicalBayesianComparison)
plot(modelTCellsBayesianComparison)
plot(modellogVLoadBayesianComparison)
```

```{r}
looMentalBayesianComparison <- loo(modelMentalBayesianComparison)
looPhysicalBayesianComparison <- loo(modelPhysicalBayesianComparison)
looTCellsBayesianComparison <- loo(modelTCellsBayesianComparison)
loologVLoadBayesianComparison <- loo(modellogVLoadBayesianComparison)
```

```{r}
# Base models with no adherence
# set priors
priors <- c(
  set_prior("normal(0, 100)", class="b"),
  set_prior("normal(0, 100)", class="Intercept"),
  set_prior("normal(0, 100)", class="sigma", lb=0))
modelMentalBayesian <- brm(MENT_DIFF ~ hard_drugs_0 + AGG_MENT_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelMentalBayesian)

modelPhysicalBayesian <- brm(PHYS_DIFF ~ hard_drugs_0 + AGG_PHYS_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelPhysicalBayesian)

modelTCellsBayesian <- brm(LEU3N_DIFF ~ hard_drugs_0 + LEU3N_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelTCellsBayesian)

modellogVLoadBayesian <- brm(logVLOAD_DIFF ~ hard_drugs_0 + logVLOAD_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modellogVLoadBayesian)
```

```{r}
plot(modelMentalBayesian)
plot(modelPhysicalBayesian)
plot(modelTCellsBayesian)
plot(modellogVLoadBayesian)
```

```{r}
looMentalBayesian <- loo(modelMentalBayesian)
looPhysicalBayesian <- loo(modelPhysicalBayesian)
looTCellsBayesian <- loo(modelTCellsBayesian)
loologVLoadBayesian <- loo(modellogVLoadBayesian)
```

```{r}
looMentalBayesianComparison$estimates["looic",1] - looMentalBayesian$estimates["looic",1]
looPhysicalBayesianComparison$estimates["looic",1] - looPhysicalBayesian$estimates["looic",1]
looTCellsBayesianComparison$estimates["looic",1] - looTCellsBayesian$estimates["looic",1]
loologVLoadBayesianComparison$estimates["looic",1] - loologVLoadBayesian$estimates["looic",1]
```

```{r}
# Models with adherence
modelMentalBayesianADH <- brm(MENT_DIFF ~ hard_drugs_0 + adherenceHigh + AGG_MENT_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelMentalBayesianADH)

modelPhysicalBayesianADH <- brm(PHYS_DIFF ~ hard_drugs_0 + adherenceHigh + AGG_PHYS_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelPhysicalBayesianADH)

modelTCellsBayesianADH <- brm(LEU3N_DIFF ~ hard_drugs_0 + adherenceHigh + LEU3N_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modelTCellsBayesianADH)

modellogVLoadBayesianADH <- brm(logVLOAD_DIFF ~ hard_drugs_0 + adherenceHigh + logVLOAD_0 + age_0 + BMI_0 + white + smoker + collegeDegree, prior=priors, warmup=10000, iter=40000, data=dfHIV)
summary(modellogVLoadBayesianADH)
```

```{r}
plot(modelMentalBayesianADH)
plot(modelPhysicalBayesianADH)
plot(modelTCellsBayesianADH)
plot(modellogVLoadBayesianADH)
```

```{r}
looMentalBayesianADH <- loo(modelMentalBayesianADH)
looPhysicalBayesianADH <- loo(modelPhysicalBayesianADH)
looTCellsBayesianADH <- loo(modelTCellsBayesianADH)
loologVLoadBayesianADH <- loo(modellogVLoadBayesianADH)
```

```{r}
looMentalBayesian$estimates["looic",1] - looMentalBayesianADH$estimates["looic",1]
looPhysicalBayesian$estimates["looic",1] - looPhysicalBayesianADH$estimates["looic",1]
looTCellsBayesian$estimates["looic",1] - looTCellsBayesianADH$estimates["looic",1]
loologVLoadBayesian$estimates["looic",1] - loologVLoadBayesianADH$estimates["looic",1]
```

```{r}
# Table of results
frequentistEstimate <- round(c(modelMentalFrequentist$coefficients["hard_drugs_0"], modelPhysicalFrequentist$coefficients["hard_drugs_0"], modelTCellsFrequentist$coefficients["hard_drugs_0"], modellogVLoadFrequentist$coefficients["hard_drugs_0"]), digits=2)

formatCIModel <- function(model, variable) {paste("(",paste(round(confint(model)[variable,], 2), collapse=", "), ")",sep="")}
formatCI <- function(ci) {paste("(",paste(round(ci, 2), collapse=", "), ")",sep="")}

frequentistCI = c(formatCIModel(modelMentalFrequentist, "hard_drugs_0"), formatCIModel(modelPhysicalFrequentist, "hard_drugs_0"), formatCIModel(modelTCellsFrequentist, "hard_drugs_0"), formatCIModel(modellogVLoadFrequentist, "hard_drugs_0"))

modelMentalFrequentistSum <- summary(modelMentalFrequentist)

pValue <- format.pval(c(summary(modelMentalFrequentist)$coefficients["hard_drugs_0",][4], summary(modelPhysicalFrequentist)$coefficients["hard_drugs_0",][4], summary(modelTCellsFrequentist)$coefficients["hard_drugs_0",][4], summary(modellogVLoadFrequentist)$coefficients["hard_drugs_0",][4]), digits=2, eps=0.001)


bayesianEstimate <- round(c(fixef(modelMentalBayesian)["hard_drugs_0",][1], fixef(modelPhysicalBayesian)["hard_drugs_0",][1], fixef(modelTCellsBayesian)["hard_drugs_0",][1], fixef(modellogVLoadBayesian)["hard_drugs_0",][1]), 2)

bayesianCI <- c(formatCI(fixef(modelMentalBayesian)["hard_drugs_0",][3:4]), formatCI(fixef(modelPhysicalBayesian)["hard_drugs_0",][3:4]), formatCI(fixef(modelTCellsBayesian)["hard_drugs_0",][3:4]), formatCI(fixef(modellogVLoadBayesian)["hard_drugs_0",][3:4]))

getPP <- function(modelDraws, threshold) {prop.table(table(modelDraws$b_hard_drugs_0 > threshold | modelDraws$b_hard_drugs_0 < -threshold))[2]}

modelMentalBayesianDraws <- as_draws_df(modelMentalBayesian)
modelPhysicalBayesianDraws <- as_draws_df(modelPhysicalBayesian)
modelTCellsBayesianDraws <- as_draws_df(modelTCellsBayesian)
modellogVLoadBayesianDraws <- as_draws_df(modellogVLoadBayesian)

pp <- format.pval(c(getPP(modelMentalBayesianDraws, 2), getPP(modelPhysicalBayesianDraws, 2), getPP(modelTCellsBayesianDraws, 50), getPP(modellogVLoadBayesianDraws, 0.5)), digits=2, eps=0.001)


dfResults <- data.frame(Variable = c("Mental Score", "Physical Score", "CD4+ T cell count", "Log(Viral Load)"),
                        FrequentistEstimate = frequentistEstimate,
                        FrequentistCI = frequentistCI,
                        PValue = pValue,
                        BayesianEstimate = bayesianEstimate,
                        BayesianCI = bayesianCI,
                        PP = pp)
```