---
title: "Project3Notes"
author: "Isabelle Meredith"
date: "2026-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes
outcome: death from stroke

include for sure: age, diabetes, blood pressure

maybe?: coronary heart disease, blood pressure medication, smoking status, total cholesterol, BMI

Just interested in baseline values for all of these

Not interested in people who have already had a stroke, so TIMESTRK = 0
Just drop them

Should remove weird values
Exclude missing?

Not interested in other events, don't worry about competing risk modeling stuff (which is good because I don't know how)

Stopping at 10 years
Pretend other years don't exist

Treat death during the study as censoring

Don't have to do time covarying analysis, just want to say whether or not it's a good future analysis and what the implications of not doing it are

account for leap years I guess lol
so 365.25*10

two datasets, one for male and one for female

we can have different covariates for male and female models, in the final model

complete case(?)


Do we want the same set of variables in the male and female models?
Can be same or different based on variable selection, just need to be able to explain why you did it that way

Censoring time is date of death if didn't die of stroke

Curves for ages 40, 50, and 60

Estimate for someone who has no risk factors
And estimates for someone with high blood pressure (160), someone with diabetes, and someone with high blood pressure and diabetes
Then one additional profile that we think is interesting based on what we include in the model

Goal is more to compare within sex
Goal is not to compare sexes but they're separate because they might be different

Censor people at the point where they die
Happens on its own anyway I think?

The high BP and cholesterol are okay

Have to keep these three no matter what: age, diabetes, blood pressure

.1 to .25 for p values for model selection


