---
title: "Project 2 Data Analysis Plan"
author: "Isabelle Meredith"
date: "2026-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project 2 Interim Data Analysis Plan

### Notes and questions
Are episodic memory and memory consolidation the same thing???? Or different measures??? Same with cortical thickness???
This is two models in the first case and four in the second
Does it make sense to do cytokines and chemokines separately? Are they considered meaningfully different in their effects? What do they each indicate? Would we ever expect to see one significant and the other not?

Is "peripheral levels of inflammation" a single measure or is it the cytokines and chemokines again??
Is memory decline one measure or several??
Is the strongest predictor claim important or do we just want to investigate if it is a strong predictor?
Not actually sure how to evaluate that?? Biggest coefficient, so long as it's significant??


### Requirements
1. For each aim, the hypotheses you will be testing, including a description of the outcome(s) and predictor(s) of interest

2. The over-all analysis approach you will be using for each hypothesis

3. How you will approach/incorporate the other data/variables available besides the outcomes and predictors of interest

4. What power/sample size calculations you will conduct for each of the hypotheses of interest

5. Not required for interim, but will be required for final: thoughts on your approach to type I error control.

### Aim 1

Higher baseline cytokine and chemokine levels in circulating plasma, indicators of inflammation, will predict declines in memory consolidation and decreases in AD-signature cortical thickness. Furthermore, greater increases in cytokines and chemokines will be associated with greater declines in episodic memory and cortical thickness. We will evaluate this using separate general linear models for cytokine and chemokine levels at baseline along with the change in levels between year 0 and year 1 with the decline in memory and cortical thickness, while controlling for age, sex, cardiovascular risk, immunological health conditions, APOE genotype, clinical dementia rating, and geriatric depression measure. All measured cytokines and chemokines will be included in the model: MCP-1, Eotaxin-1, IL-6, and TNF-alpha. A separate model will be run for each measure of memory decline: a list learning measure, figure recall, the mnemonic similarity task, and long term consolidation.



### Aim 2
We will test our hypothesis of an interaction between peripheral levels of inflammation and amyloid deposition,
such that the presence of both significant amyloid deposition and elevated peripheral inflammatory markers will
be the strongest predictors of memory decline and decline in AD-signature cortical thickness over a one year
period.

## Aim 1 Notes

Based on current clinic flow and participant study consents, we can expect to recruit two to three participants per week; considering the projected 10% attrition over the follow-up period, we plan to recruit 138 aMCI and 56 HC to reach our two-time point goal of 125 aMCI and 50 HC subjects (ages 60–90 years)

a) Higher baseline cytokine and chemokine levels in circulating plasma, indicators of inflammation, will predict declines in memory consolidation and decreases in AD-signature cortical thickness

b) greater increases in cytokines and chemokines will be associated with greater declines in episodic memory and cortical thickness 

Predictors: 
a)
Chemokines: MCP-1; Eotaxin-1
Cytokines: IL-6; TNF-alpha
baseline cytokine levels
baseline chemokine levels
b)
change in cytokine
change in chemokine

Outcomes: 
a)
memory consolidation
AD-signature cortical thickness
b)
episodic memory
cortical thickness

Section in document
I have to adjust for age and sex and anything else you tell me needs to be adjusted for. For example, how will we handle the known associations between inflammation, cardiovascular risk, immunological health history conditions, and APOE genotype? Also there are correlations between the health measures (i.e. BMI, history of
hypercholesterolemia, NSAID use; immune-related health conditions)

### Aim 2 Notes


We will test our hypothesis of an interaction between peripheral levels of inflammation and amyloid deposition,
such that the presence of both significant amyloid deposition and elevated peripheral inflammatory markers will
be the strongest predictors of memory decline and decline in AD-signature cortical thickness over a one year
period. We will evaluate this using general linear models for the decline in THE OUTCOME MEASURES with amyloid deposition, peripheral inflammatory markers, and an interaction between the two, while controlling for age, sex, and WHICHEVER SEEMS MOST IMPORTANT.

Predictors
peripheral levels of inflammation
amyloid deposition
interaction between the two

Outcomes
memory decline
decline in AD-signature cortical thickness

Section in document
As in Aim 1 we need to control for age and sex. Also confounders?? Not sure of best way to model my hypothesis
about the combination of amyloid deposition and peripheral inflammation being worse than either alone.


clinical dementia rating
depression measure





